apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pc3eotki5-python 
  janus-idp.io/tekton: pc3eotki5-python
  backstage.io/kubernetes-id: pc3eotki5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pc3eotki5-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml