apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pc3eotki5-python-gitops
  description: This is GitOps manifest for pc3eotki5-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=pc3eotki5-python
    backstage.io/kubernetes-id: pc3eotki5-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: pc3eotki5-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:pc3eotki5-python
